import { execSync } from "node:child_process";
import { mkdirSync, writeFileSync, copyFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const STACKS_YML_CONTENT = `# Canonical Tech Stacks — auto-generated by repo-setup
website:
  framework: nextjs
  bundler: turbopack
  styling: tailwindcss-v4
  state:
    server: tanstack-query
    client: zustand
  language: typescript
  package_manager: npm

backend:
  runtime: nextjs-api-routes
  database: convex
  payments: stripe

deployment:
  frontend: vercel
  frontend_cli: vercel-cli
  backend: railway
  backend_cli: railway-cli
  ci_cd: github-actions

quality:
  code_review: cubic
  testing:
    unit: vitest
    e2e: playwright
    strategy: tdd
`;

const GITIGNORE_CONTENT = `# Dependencies
node_modules/

# Build outputs
dist/
.next/
out/
.vercel/

# Environment
.env
.env.local
.env.production

# Convex
.convex/

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Test
coverage/

# Secrets
*.pem
*.key
`;

const CI_WORKFLOW_CONTENT = `name: CI
on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run test
`;

export interface ScaffoldOptions {
  name: string;
  org?: string;
  templateDir?: string;
  private?: boolean;
}

export interface ExecRunner {
  (command: string, options?: { cwd?: string }): string;
}

const defaultExec: ExecRunner = (command, options) => {
  return execSync(command, {
    encoding: "utf-8",
    cwd: options?.cwd,
    stdio: "pipe",
  });
};

export function createGitHubRepo(
  options: ScaffoldOptions,
  exec: ExecRunner = defaultExec
): string {
  const visibility = options.private ? "--private" : "--public";
  const repoName = options.org
    ? `${options.org}/${options.name}`
    : options.name;

  exec(`gh repo create ${repoName} ${visibility} --clone`);
  return repoName;
}

export function copyWebsiteTemplate(
  projectDir: string,
  templateDir: string,
  exec: ExecRunner = defaultExec
): void {
  if (!existsSync(templateDir)) {
    throw new Error(`Template directory not found: ${templateDir}`);
  }
  exec(`cp -r ${templateDir}/. ${projectDir}/`);
}

export function generateTaskfile(projectDir: string): void {
  const taskfileContent = `version: "3"

tasks:
  dev:
    desc: Start development server
    cmds:
      - npm run dev

  test:
    desc: Run all tests
    cmds:
      - npm run test

  build:
    desc: Build for production
    cmds:
      - npm run build

  deploy:
    desc: Deploy to production
    cmds:
      - vercel --prod

  lint:
    desc: Run linter
    cmds:
      - npm run lint

  typecheck:
    desc: Run TypeScript type checking
    cmds:
      - npx tsc --noEmit

  feature:list:
    desc: List all features and their status
    cmds:
      - ls -la features/

  feature:status:
    desc: Show status of a specific feature
    cmds:
      - cat features/{{.FEATURE}}.md
`;
  writeFileSync(join(projectDir, "Taskfile.yml"), taskfileContent);
}

export function setupFeaturesDir(projectDir: string): void {
  const featuresDir = join(projectDir, "features");
  mkdirSync(featuresDir, { recursive: true });
  writeFileSync(
    join(featuresDir, ".gitkeep"),
    "# Feature checklists live here\n"
  );
}

export function setupHarnessConfigs(projectDir: string): void {
  const harnessDir = join(projectDir, ".harness");
  mkdirSync(harnessDir, { recursive: true });
  writeFileSync(join(harnessDir, "stacks.yml"), STACKS_YML_CONTENT);
}

export function setupGitignore(projectDir: string): void {
  writeFileSync(join(projectDir, ".gitignore"), GITIGNORE_CONTENT);
}

export function setupCIWorkflow(projectDir: string): void {
  const workflowDir = join(projectDir, ".github", "workflows");
  mkdirSync(workflowDir, { recursive: true });
  writeFileSync(join(workflowDir, "ci.yml"), CI_WORKFLOW_CONTENT);
}

export function scaffold(
  options: ScaffoldOptions,
  exec: ExecRunner = defaultExec
): string {
  const repoName = createGitHubRepo(options, exec);
  const projectDir = join(process.cwd(), options.name);

  if (options.templateDir) {
    copyWebsiteTemplate(projectDir, options.templateDir, exec);
  }

  generateTaskfile(projectDir);
  setupFeaturesDir(projectDir);
  setupHarnessConfigs(projectDir);
  setupGitignore(projectDir);
  setupCIWorkflow(projectDir);

  return repoName;
}
